const router = require('express').Router( )
const auth = require('../validate/authorization')
const duplicate = require('../validate/dublicate')
const userController = require('../controller/user.controller')
const {usersValidation , passwordValidation,emailValidation,loginValidation} = require('../validate/users')
router.get('/',userController.getall)
router.get('/:id',userController.getallById)
router.post('/createUser',usersValidation,duplicate.user,userController.create)
router.delete('/:id',userController.deleteById)
router.post('/login',loginValidation,userController.login)
router.post('/logout',userController.logout)
router.post('/checkUser',emailValidation,userController.checkUser)
router.post('/reset',auth.checkResetToken,passwordValidation,userController.reset)
router.post('/getAcessToken',auth.checkRefreshToken,userController.getAcessToken)
router.put('/activeAccount',auth.checkActiveAccountToken,userController.active)
module.exports = router